name: Test, Build and Release
on:
    workflow_dispatch:
    push:
        branches: [main, develop]

jobs:
    
    versioning:
      name: determine current and possible next versions
      # needs: unittest
      runs-on: ubuntu-latest
      outputs:
        currentmajorversion: ${{ steps.getalltags.outputs.currentmajorversion }}

      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Get version data
          id: getalltags
          run: |
            declare -i currentmajorversion=$(git describe --tag $(git rev-parse --verify refs/remotes/origin/main) | cut -c 2- | cut -d'.' -f1)
            echo "currentmajorversion=$currentmajorversion"
            declare -i nextmajorversion=$currentmajorversion+1
            echo "nextmajorversion=$nextmajorversion"
