name: Test, Build and Release
on:
    workflow_dispatch:
    push:
        branches: [main, develop]

jobs:
    
    versioning:
      name: determine current and possible next versions
      # needs: unittest
      runs-on: ubuntu-latest
      outputs:
        currentmajornmbr: ${{ steps.versioninfo.outputs.currentmajornmbr }}
        currentminornmbr: ${{ steps.versioninfo.outputs.currentminornmbr }}
        currentpatchnmbr: ${{ steps.versioninfo.outputs.currentpatchnmbr }}
        nextmajornmbr: ${{ steps.versioninfo.outputs.nextmajornmbr }}
        nextminornmbr: ${{ steps.versioninfo.outputs.nextminornmbr }}
        nextpatchnmbr: ${{ steps.versioninfo.outputs.nextpatchnmbr }}
        currentversion: ${{ steps.versioninfo.outputs.currentversion }}
        nextmajorversion: ${{ steps.versioninfo.outputs.nextmajorversion }}
        nextminorversion: ${{ steps.versioninfo.outputs.nextminorversion }}
        nextpatchversion: ${{ steps.versioninfo.outputs.nextpatchversion }}

      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Get version data
          id: versioninfo
          run: |
            echo "extract SemVer numbers from repository tags"
            declare -i currentmajornmbr=$(git describe --tag $(git rev-parse --verify refs/remotes/origin/main) | cut -c 2- | cut -d'.' -f1)
            declare -i nextmajornmbr=$currentmajornmbr+1
            echo "currentmajornmbr = $currentmajornmbr, nextmajornmbr = $nextmajornmbr"
            declare -i currentminornmbr=$(git describe --tag $(git rev-parse --verify refs/remotes/origin/main) | cut -c 2- | cut -d'.' -f2)
            declare -i nextminornmbr=$currentminornmbr+1
            echo "currentminornmbr = $currentminornmbr, nextminornmbr = $nextminornmbr"
            declare -i currentpatchnmbr=$(git describe --tag $(git rev-parse --verify refs/remotes/origin/main) | cut -c 2- | cut -d'.' -f3)
            declare -i nextpatchnmbr=$currentpatchnmbr+1
            echo "currentpatchnmbr = $currentpatchnmbr, nextpatchnmbr = $nextpatchnmbr"
            echo "assemble complete version strings, for current and possible next versions"
            declare currentversion="v$currentmajornmbr.$currentminornmbr.$currentpatchnmbr"
            declare nextmajorversion="v$nextmajornmbr.$currentminornmbr.$currentpatchnmbr"
            declare nextminorversion="v$currentmajornmbr.$nextminornmbr.$currentpatchnmbr"
            declare nextpatchversion="v$currentmajornmbr.$currentminornmbr.$nextpatchnmbr"
            echo "output to GitHub Actions output variables"
            echo "currentversion=$currentversion" >> $GITHUB_OUTPUT
            echo "nextmajorversion=$nextmajorversion" >> $GITHUB_OUTPUT
            echo "nextminorversion=$nextminorversion" >> $GITHUB_OUTPUT
            echo "nextpatchversion=$nextpatchversion" >> $GITHUB_OUTPUT

        - name: Version Test
          id: versiontester
          run: |
            echo "checking github output variables : "
            echo "Current version : ${{ steps.versioninfo.outputs.currentversion }}"
            echo "Next major version : ${{ steps.versioninfo.outputs.nextmajorversion }}"
            echo "Next minor version : ${{ steps.versioninfo.outputs.nextminorversion }}"
            echo "Next patch version : ${{ steps.versioninfo.outputs.nextpatchversion }}"

